services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qtim
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_DATABASE: "qtim"
      DB_POSTGRES_USER: "postgres"
      DB_POSTGRES_PASSWORD: "postgres"
      DB_POSTGRES_DEBUG: "false"
      JWT_SECRET: "secret"
      PORT: "3000"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: